seo:
  site_name: Kulinaria - Bistro & Restaurant & Catering
  title: Kulinaria - Bistro & Restaurant & Catering
  description: Restaurant & Catering mit frisch zubereiteten Speisen.
  keywords: Wechselnde Speisekarte, frische Zutaten, Westerwald,
  social_image: /images/logo.jpg
  author: Kulinaria, André Champaert
social:
  instagram_username:
  facebook_url:
design:
  dark_color: '#60423e'
  soft_color: '#998685'
  light_color: '#ad9e9c'
  white_color: '#fff'

